---
- name: deploy to Tomcat 
  hosts: all
  become: true

  tasks:
   - name: Download an artifact from Nexus repository and deploy to tomcat server
     maven_artifact:
      group_id: com.tcs.angularjs
      artifact_id: springbootApp
      extension: jar
      repository_url: 'http://13.232.127.233:8081/repository/simpleapp/'
      version: "${mavenPom.version}"
      username: admin
      password: admin123
      dest: /usr/local/apache-tomcat-9.0.68/webapps/
